version: '3.4'

services:
  
  database:
    image: mariadb
    # restart: always
    ports: 
      - 3306:3306
    networks:
      - network_services
    environment:
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_ROOT_PASSWORD: root
    volumes:
        - ./database:/var/lib/database

  phpmyadmin:
    image: phpmyadmin
    # restart: always
    ports:
      - 8069:80
    networks:
      - network_services
    environment:
      PMA_HOST: database

  php:
    # restart: always
    build: ./php
    working_dir: /var/www/html
    links:
      - database
    networks:
      - network_services
    volumes:
      - ./php/src:/var/www/html
      - ./php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - /var/www/html/vendor

  nginx:
    build: ./nginx
    working_dir: /var/www/html
    volumes_from:
      - php
    networks:
      - network_services
    volumes:
      - ./nginx/ssl:/etc/ssl
    ports:
      - 8009:80
      - 443:443

networks:
  network_services:
    driver: bridge   