FROM php:8.0-fpm

# Expose port 80 and 443
EXPOSE 80
EXPOSE 443

# Timezone
ENV TZ=Asia/Bangkok
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone


# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    libwebp-dev \ 
    libxpm-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    libicu-dev \
    libmcrypt-dev \
    libxslt1-dev \
    nodejs \
    npm \
    unzip \
    mariadb-client \
    cron

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-configure \
    gd --with-freetype=/usr/include/ --with-jpeg=/usr/include/

RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd intl soap xsl


# Get latest Composer
RUN curl -sS https://getcomposer.org/installer | \
  php -- --install-dir=/usr/local/bin --filename=composer

COPY src/ /var/www/html
COPY src/.env.example /var/www/html/.env

# Set working directory
WORKDIR /var/www/html

# Install composer based on Laravel composer.json
# RUN php composer update
# RUN php composer.phar update
RUN composer install
# RUN php composer update

# RUN bash -c "composer require jenssegers/agent"

# RUN composer require laravel/ui

# Change permission
RUN chown -R www-data:root /var/www/html

#copy env
# RUN cp .env.example .env

# Laravel generate Application Key
RUN php artisan key:generate

# Install composer based on Laravel composer.json, Change permission and Laravel generate Application Key
# RUN composer install && chown -R www-data:root /var/www/html && php artisan key:generate

# COPY backup_cron /etc/cron.d/backup_cron

# COPY backup_cron.sh /var/www/backup_cron.sh

# RUN chmod 0644 /etc/cron.d/backup_cron && chmod 0755 /var/www/backup_cron.sh

# RUN crontab /etc/cron.d/backup_cron

# RUN touch /var/log/cron.log

# CMD /etc/init.d/cron start && docker-php-entrypoint php-fpm

# CMD /etc/init.d/cron start && tail -f /var/log/cron.log

# CMD cron && tail -f /var/log/cron.log